# Generated by Django 4.0.3 on 2022-03-15 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gs_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ratings',
            field=models.ManyToManyField(blank=True, null=True, related_name='games_rated', through='gs_django_app.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='threads',
            field=models.ManyToManyField(blank=True, null=True, related_name='games_threaded', through='gs_django_app.Thread', to=settings.AUTH_USER_MODEL),
        ),
    ]
