# Generated by Django 4.0.3 on 2022-03-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0003_alter_game_ratings_alter_game_threads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='game',
            name='threads',
        ),
    ]
