# Generated by Django 4.0.3 on 2022-03-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0005_game_ratings_game_threads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='genre',
            new_name='genre_1',
        ),
        migrations.AddField(
            model_name='game',
            name='genre_2',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('adventure', 'Adventure'), ('fighting', 'Fighting'), ('rpg', 'RPG'), ('racing', 'Racing'), ('shooter', 'Shooter'), ('simulation', 'Simulation'), ('sports', 'Sports'), ('other', 'Other')], max_length=128, null=True),
        ),
    ]
