# Generated by Django 4.0.3 on 2022-03-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0007_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='gs_django_app.series'),
        ),
    ]
