# Generated by Django 4.0.3 on 2022-03-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0012_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
