# Generated by Django 4.0.3 on 2022-03-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0014_alter_comment_text_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre_1',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('fighting', 'Fighting'), ('rpg', 'RPG'), ('racing', 'Racing'), ('shooter', 'Shooter'), ('simulation', 'Simulation'), ('sports', 'Sports'), ('stealth', 'Stealth'), ('other', 'Other')], max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre_2',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('adventure', 'Adventure'), ('fighting', 'Fighting'), ('rpg', 'RPG'), ('racing', 'Racing'), ('shooter', 'Shooter'), ('simulation', 'Simulation'), ('sports', 'Sports'), ('stealth', 'Stealth'), ('other', 'Other')], max_length=128, null=True),
        ),
    ]
