# Generated by Django 4.0.3 on 2022-03-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0016_alter_game_genre_1_alter_game_genre_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture_url',
            field=models.CharField(max_length=256),
        ),
    ]
