# Generated by Django 4.0.3 on 2022-04-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0017_alter_game_picture_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('name', 'publisher')},
        ),
    ]
