# Generated by Django 4.0.3 on 2022-04-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0019_alter_company_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre_1',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Fighting', 'Fighting'), ('Role playing', 'Role playing'), ('Racing', 'Racing'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Stealth', 'Stealth'), ('Other', 'Other')], max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre_2',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Fighting', 'Fighting'), ('Role playing', 'Role playing'), ('Racing', 'Racing'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Stealth', 'Stealth'), ('Other', 'Other')], max_length=128, null=True),
        ),
    ]
