# Generated by Django 4.0.3 on 2022-04-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0020_alter_game_genre_1_alter_game_genre_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
