# Generated by Django 4.0.3 on 2022-04-06 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gs_django_app', '0024_rename_title_thread_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='game',
            name='threads',
        ),
        migrations.AddField(
            model_name='game',
            name='posts',
            field=models.ManyToManyField(related_name='games_posted', through='gs_django_app.Post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='posts', through='gs_django_app.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gs_django_app.game'),
        ),
        migrations.AddField(
            model_name='post',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='gs_django_app.post'),
        ),
    ]
