# Generated by Django 4.0.3 on 2022-04-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0026_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_closed',
        ),
    ]
