# Generated by Django 4.0.3 on 2022-04-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0027_remove_post_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='starter',
            new_name='user',
        ),
    ]
