# Generated by Django 4.0.4 on 2022-04-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0035_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
