# Generated by Django 4.0.4 on 2022-04-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0036_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at',)},
        ),
    ]
