# Generated by Django 4.0.4 on 2022-04-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0041_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at', 'text')},
        ),
        migrations.AlterModelOptions(
            name='commentresponse',
            options={'ordering': ('created_at', 'response')},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('name', 'release_year')},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at', 'text')},
        ),
        migrations.AlterModelOptions(
            name='postresponse',
            options={'ordering': ('created_at', 'response')},
        ),
        migrations.AlterField(
            model_name='game',
            name='genre_1',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Battle', 'Battle'), ('Board', 'Board'), ('Casino', 'Casino'), ('Fighting', 'Fighting'), ('Flight', 'Flight'), ('Hunting', 'Hunting'), ('Puzzle', 'Puzzle'), ('Role playing', 'Role playing'), ('Racing', 'Racing'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Stealth', 'Stealth'), ('Strategy', 'Strategy'), ('Trivia', 'Trivia'), ('Wrestling', 'Wrestling'), ('Other', 'Other')], max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre_2',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Battle', 'Battle'), ('Board', 'Board'), ('Casino', 'Casino'), ('Fighting', 'Fighting'), ('Flight', 'Flight'), ('Hunting', 'Hunting'), ('Puzzle', 'Puzzle'), ('Role playing', 'Role playing'), ('Racing', 'Racing'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Stealth', 'Stealth'), ('Strategy', 'Strategy'), ('Trivia', 'Trivia'), ('Wrestling', 'Wrestling'), ('Other', 'Other')], max_length=128, null=True),
        ),
    ]
