# Generated by Django 4.0.4 on 2022-05-12 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gs_django_app', '0042_alter_comment_options_alter_commentresponse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('details', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=256)),
                ('spam', models.BinaryField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ('created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='commentresponse',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentResponse',
        ),
    ]
