# Generated by Django 4.0.4 on 2022-05-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0043_note_remove_commentresponse_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='details',
            new_name='info',
        ),
    ]
