# Generated by Django 4.0.4 on 2022-05-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0044_rename_details_note_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='spam',
        ),
    ]
