# Generated by Django 4.0.4 on 2022-05-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs_django_app', '0045_remove_note_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='spam',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
